runtime: java
env: flex
api_version: 1

handlers:
  - url: .*
    script: dynamic

resources:
  cpu: 1
  memory_gb: 2

# Specify the active profile of spring for production environment by environment variable.
env_variables:
  SPRING_PROFILES_ACTIVE: 'prod'
